"""Estimated API-equivalent cost for gateway requests.

The gateway's own billing runs on WorkBuddy credits: the `credit` field of a
usage row answers "how much did this request consume from the account". This
module answers a different question - "what would the same tokens have cost at
OpenRouter's listed price" - by pricing every usage row against a snapshot of
OpenRouter's model catalogue (USD per token, the model-level price OpenRouter
publishes rather than the cheapest provider behind it), converted at the
snapshot's usd_cny rate.

Every model is priced from that single source. Most carry one flat price; the
ones OpenRouter prices conditionally carry bands instead - a dearer rate above
an input-length threshold, or a rate that varies with UTC time of day - and the
row's own length and timestamp pick the band. Either way the figure is an
estimate of equivalent token cost, not what the gateway actually billed.

The inline snapshot (same pattern as wb_catalog) is the price the Docker image
ships with; `_fetch_pricing.py` regenerates it, and a `pricing/pricing.json`
next to this script (or the path in WB_PRICING_FILE) overrides the inline copy.
At run time PriceRefresher stores what it fetches as per-model policies keyed by
a hash of their own content, plus a timeline saying which policy each model was
on at any moment. A price that has been seen before is reused rather than written
again, a request records a reference to the policy that priced it, and policies
nothing points at are swept - except a model's live one, the batch just fetched,
and a model's last row of all. All prices are per `unit` tokens (1M) and the
result is CNY; callers divide by meta.usd_cny to show USD.

A model the upstream adds is priced without a release. The fetch input is the
bundled catalogue plus whatever the gateway's live catalogue lists beyond it, so
a new name enters the next cycle on its own; a model called before that cycle
is priced on demand from the index the last fetch left in memory (no network on
the request path). A name carrying a channel suffix the base name does not
(`deepseek-r1-0528-lkeap`) inherits from the suffix-stripped base, but only when
that base matches OpenRouter uniquely - a guess is never written down. A model
that still cannot be priced is listed by the panel with the reason and, where
one exists, a hand-entered mapping that lives in the data folder rather than in
this file.

Only the Python standard library is required.
"""

import bisect
import hashlib
import json
import os
import re
import sys
import threading
import time
import urllib.request

# Snapshot generated by _fetch_pricing.py - see that script for the sources
# and the refresh procedure. The inline copy is the fallback every install
# (including the Docker image) has.
_JSON = r'''
{
  "meta": {
    "generated_at": "2026-10-02T01:39:39",
    "base_currency": "CNY",
    "usd_cny": 7.1,
    "sources": {
      "openrouter": "https://openrouter.ai/api/v1/models"
    },
    "note": "单价均为「每百万 token」的美元价，取自 OpenRouter 公布的模型级价（同一模型可能由多家 provider 承接，取它默认路由那家的公布价，不是各家最低价）；按 usd_cny 折算成人民币；按条件定价的模型（输入长度阈值或 UTC 时段）另带 bands，按每条请求的输入长度与时间取档。OpenRouter 的缓存写入价与音频价，本地 usage 日志没有对应的 token 数，未计入。"
  },
  "models": {
    "deepseek-v4.1-flash": {
      "display": "deepseek-v4.1-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4.1-flash",
      "flat": {
        "input_cache_hit": 0.01,
        "input_cache_miss": 0.03,
        "output": 0.5
      }
    },
    "gpt-6-astra": {
      "display": "gpt-6-astra",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-6-astra",
      "flat": {
        "input_cache_hit": 1.0,
        "input_cache_miss": 10.0,
        "output": 50.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 2.0,
            "input_cache_miss": 20.0,
            "output": 75.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "hy4-preview-f": {
      "display": "hy4-preview-f",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview": {
      "display": "hy4-preview",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy3": {
      "display": "hy3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy3",
      "flat": {
        "input_cache_hit": 0.020625,
        "input_cache_miss": 0.0825,
        "output": 0.33
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.033,
            "input_cache_miss": 0.132,
            "output": 0.528
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.020625,
            "input_cache_miss": 0.0825,
            "output": 0.33
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "gpt-5.6-sol": {
      "display": "gpt-5.6-sol",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-sol",
      "flat": {
        "input_cache_hit": 0.2,
        "input_cache_miss": 2.0,
        "output": 10.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.4,
            "input_cache_miss": 4.0,
            "output": 15.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.6-terra": {
      "display": "gpt-5.6-terra",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-terra",
      "flat": {
        "input_cache_hit": 0.2,
        "input_cache_miss": 2.0,
        "output": 12.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.4,
            "input_cache_miss": 4.0,
            "output": 18.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.6-luna": {
      "display": "gpt-5.6-luna",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-luna",
      "flat": {
        "input_cache_hit": 0.02,
        "input_cache_miss": 0.2,
        "output": 1.2
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.04,
            "input_cache_miss": 0.4,
            "output": 1.8
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.5": {
      "display": "gpt-5.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.5",
      "flat": {
        "input_cache_hit": 0.5,
        "input_cache_miss": 5.0,
        "output": 30.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 1.0,
            "input_cache_miss": 10.0,
            "output": 45.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.4": {
      "display": "gpt-5.4",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.4",
      "flat": {
        "input_cache_hit": 0.25,
        "input_cache_miss": 2.5,
        "output": 15.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.5,
            "input_cache_miss": 5.0,
            "output": 22.5
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "grok-4.7": {
      "display": "grok-4.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "x-ai/grok-4.7",
      "flat": {
        "input_cache_hit": 0.5,
        "input_cache_miss": 2.0,
        "output": 6.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 1.0,
            "input_cache_miss": 4.0,
            "output": 12.0
          },
          "min_prompt_tokens": 200000
        }
      ]
    },
    "gpt-5.3-codex": {
      "display": "gpt-5.3-codex",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.3-codex",
      "flat": {
        "input_cache_hit": 0.175,
        "input_cache_miss": 1.75,
        "output": 14.0
      }
    },
    "gemini-3.5-flash": {
      "display": "gemini-3.5-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "google/gemini-3.5-flash",
      "flat": {
        "input_cache_hit": 0.15,
        "input_cache_miss": 1.5,
        "output": 9.0
      }
    },
    "glm-5.3": {
      "display": "glm-5.3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.3",
      "flat": {
        "input_cache_hit": 0.192,
        "input_cache_miss": 0.24,
        "output": 3.39
      }
    },
    "glm-5.3-flash": {
      "display": "glm-5.3-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.3-flash",
      "flat": {
        "input_cache_hit": 0.03,
        "input_cache_miss": 0.15,
        "output": 0.5
      }
    },
    "glm-5.2": {
      "display": "glm-5.2",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.2",
      "flat": {
        "input_cache_hit": 0.26,
        "input_cache_miss": 0.41,
        "output": 3.99
      }
    },
    "kimi-k3": {
      "display": "kimi-k3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k3",
      "flat": {
        "input_cache_hit": 0.6635,
        "input_cache_miss": 0.6635,
        "output": 10.0
      }
    },
    "kimi-k2.6": {
      "display": "kimi-k2.6",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.6",
      "flat": {
        "input_cache_hit": 0.07312,
        "input_cache_miss": 0.43415,
        "output": 1.828
      }
    },
    "hy3-x": {
      "display": "hy3-x",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy3",
      "flat": {
        "input_cache_hit": 0.020625,
        "input_cache_miss": 0.0825,
        "output": 0.33
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.033,
            "input_cache_miss": 0.132,
            "output": 0.528
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.020625,
            "input_cache_miss": 0.0825,
            "output": 0.33
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview-dev": {
      "display": "hy4-preview-dev",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview-x": {
      "display": "hy4-preview-x",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "minimax-m2.5": {
      "display": "minimax-m2.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m2.5",
      "flat": {
        "input_cache_hit": 0.027,
        "input_cache_miss": 0.27,
        "output": 1.08
      }
    },
    "glm-5v-turbo": {
      "display": "glm-5v-turbo",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5v-turbo",
      "flat": {
        "input_cache_hit": 0.24,
        "input_cache_miss": 1.2,
        "output": 4.0
      }
    },
    "glm-5.1": {
      "display": "glm-5.1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.1",
      "flat": {
        "input_cache_hit": 0.17914,
        "input_cache_miss": 0.9646,
        "output": 3.0316
      }
    },
    "glm-5.0-turbo": {
      "display": "glm-5.0-turbo",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5-turbo",
      "flat": {
        "input_cache_hit": 0.24,
        "input_cache_miss": 1.2,
        "output": 4.0
      }
    },
    "glm-4.6v": {
      "display": "glm-4.6v",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-4.6v",
      "flat": {
        "input_cache_hit": 0.05,
        "input_cache_miss": 0.3,
        "output": 0.9
      }
    },
    "kimi-k3-1": {
      "display": "kimi-k3-1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k3",
      "flat": {
        "input_cache_hit": 0.6635,
        "input_cache_miss": 0.6635,
        "output": 10.0
      }
    },
    "kimi-k2.7": {
      "display": "kimi-k2.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.7-code",
      "flat": {
        "input_cache_hit": 0.18,
        "input_cache_miss": 0.6712,
        "output": 3.35
      }
    },
    "kimi-k2.5": {
      "display": "kimi-k2.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.5",
      "flat": {
        "input_cache_hit": 0.07,
        "input_cache_miss": 0.45,
        "output": 2.25
      }
    },
    "kimi-k2-thinking": {
      "display": "kimi-k2-thinking",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2-thinking",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.6,
        "output": 2.5
      }
    },
    "minimax-m3": {
      "display": "minimax-m3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m3",
      "flat": {
        "input_cache_hit": 0.06,
        "input_cache_miss": 0.3,
        "output": 1.2
      }
    },
    "minimax-m2.7": {
      "display": "minimax-m2.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m2.7",
      "flat": {
        "input_cache_hit": 0.042,
        "input_cache_miss": 0.21,
        "output": 0.84
      }
    },
    "glm-4.6": {
      "display": "glm-4.6",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-4.6",
      "flat": {
        "input_cache_hit": 0.08,
        "input_cache_miss": 0.43,
        "output": 1.75
      }
    },
    "deepseek-v4-flash": {
      "display": "deepseek-v4-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4-flash",
      "flat": {
        "input_cache_hit": 0.008372,
        "input_cache_miss": 0.04186,
        "output": 0.08372
      }
    },
    "deepseek-v4-pro": {
      "display": "deepseek-v4-pro",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4-pro",
      "flat": {
        "input_cache_hit": 0.0174,
        "input_cache_miss": 0.2088,
        "output": 0.4176
      }
    },
    "deepseek-v3-2-volc": {
      "display": "deepseek-v3-2-volc",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v3.2",
      "flat": {
        "input_cache_hit": 0.028,
        "input_cache_miss": 0.28,
        "output": 0.42
      }
    },
    "deepseek-v3-1-volc": {
      "display": "deepseek-v3-1-volc",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3.1",
      "flat": {
        "input_cache_hit": 0.13,
        "input_cache_miss": 0.25,
        "output": 0.95
      }
    },
    "deepseek-v3-1": {
      "display": "deepseek-v3-1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3.1",
      "flat": {
        "input_cache_hit": 0.13,
        "input_cache_miss": 0.25,
        "output": 0.95
      }
    },
    "deepseek-r1-0528": {
      "display": "deepseek-r1-0528",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-r1-0528",
      "flat": {
        "input_cache_hit": 0.35,
        "input_cache_miss": 0.5,
        "output": 2.15
      }
    },
    "deepseek-v3-0324": {
      "display": "deepseek-v3-0324",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3-0324",
      "flat": {
        "input_cache_hit": 0.11,
        "input_cache_miss": 0.29,
        "output": 1.14
      }
    },
    "hunyuan-2.0-instruct": {
      "display": "hunyuan-2.0-instruct",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hunyuan-a13b-instruct",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.14,
        "output": 0.57
      }
    },
    "hunyuan-chat": {
      "display": "hunyuan-chat",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hunyuan-a13b-instruct",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.14,
        "output": 0.57
      }
    }
  }
}
'''

_INLINE = json.loads(_JSON)

_lock = threading.Lock()
_file_cache = {"key": None, "data": None}


def _candidate_file():
    """The out-of-band snapshot path, or None when none is configured."""
    env = os.environ.get("WB_PRICING_FILE")
    if env:
        return env
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "pricing", "pricing.json")
    return path if os.path.isfile(path) else None


def load_pricing():
    """The active pricing snapshot, reloaded when the file changes.

    The file (when present) wins over the inline copy so an operator can
    drop a refreshed snapshot next to the script without rebuilding; the
    inline copy keeps a broken or missing file from taking pricing down.
    """
    path = _candidate_file()
    key = ("inline", 0)
    if path:
        try:
            key = (path, os.path.getmtime(path))
        except OSError:
            path = None
            key = ("inline", 0)
    with _lock:
        if _file_cache["key"] == key and _file_cache["data"] is not None:
            return _file_cache["data"]
    data = None
    if path:
        try:
            with open(path, encoding="utf-8") as fh:
                loaded = json.load(fh)
            if isinstance(loaded, dict) and isinstance(loaded.get("models"), dict):
                data = loaded
        except Exception:
            data = None
    if data is None:
        data = _INLINE
    with _lock:
        _file_cache.update({"key": key, "data": data})
    return data


def _as_float(value, default=0.0):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


_WEEKDAYS = ("mon", "tue", "wed", "thu", "fri", "sat", "sun")


def _utc_parts(epoch_sec):
    """(weekday, HHMM) at UTC, the timezone the source states its bands in.

    The gateway can run in a container on UTC and the panel is opened from
    any timezone, so the lookup must not depend on the host clock's zone.
    """
    t = time.gmtime(_as_float(epoch_sec))
    return _WEEKDAYS[t.tm_wday], t.tm_hour * 100 + t.tm_min


def _band_applies(band, prompt_tokens, day, hhmm):
    """Whether a band's condition holds for this row.

    A band carries one of two conditions - a minimum input length, or a UTC
    window; the source never mixes the two within one entry.
    """
    threshold = band.get("min_prompt_tokens")
    if threshold is not None:
        return prompt_tokens >= _as_float(threshold)
    days = band.get("days")
    if days and day not in days:
        return False
    start = _as_float(band.get("start"))
    end = _as_float(band.get("end")) or 2400.0
    return start <= hhmm < end


def band_for(entry, epoch_sec, prompt_tokens=0.0):
    """The rate table for this row, with the band index it came from.

    OpenRouter prices some models conditionally: a dearer rate once the input
    passes a length threshold, or a rate that depends on UTC time of day. The
    bands are kept in the source's order and the *last* one that applies wins.
    The source lists length bands in ascending threshold order, so taking the
    last match picks the tightest one instead of the first that happens to
    fit; the window bands do not overlap, so the same rule holds for them.

    A model without bands, or a row that satisfies none of them, falls back to
    the model's own flat price - the estimate degrades to the single-price
    behaviour rather than to zero. The index is None when that happened.
    """
    bands = entry.get("bands")
    if isinstance(bands, list) and bands:
        day, hhmm = _utc_parts(epoch_sec)
        hit = None
        for index, band in enumerate(bands):
            if not isinstance(band, dict):
                continue
            if not _band_applies(band, prompt_tokens, day, hhmm):
                continue
            table = band.get("flat")
            if isinstance(table, dict):
                hit = (table, index)
        if hit:
            return hit
    table = entry.get("flat")
    return (table if isinstance(table, dict) else {}), None


def _rate_for(entry, epoch_sec, prompt_tokens, meta):
    """The rate table for this row, its band index, and the CNY factor."""
    table, band = band_for(entry, epoch_sec, prompt_tokens)
    factor = 1.0
    if str(entry.get("currency") or "").upper() == "USD":
        factor = _as_float(meta.get("usd_cny"), 1.0) or 1.0
    return table, band, factor


def _pick(rate, key, fallback=None):
    """A per-million rate, falling back to a conservative neighbour.

    A row without a cache-hit price is billed at the miss price (never
    cheaper than the reference engine), so the estimate cannot understate
    the cost.
    """
    value = rate.get(key)
    if value is None and fallback:
        value = rate.get(fallback)
    return _as_float(value)


def compute_row(row, pricing=None):
    """The estimated cost of one usage row, in CNY.

    Returns {"cny": float, "known": bool, "band": int|None, "rates": dict|None}.
    known=False means the model has no price entry - cny stays 0 and the caller
    reports it as unpriced instead of guessing. band is the time-of-day band the
    row's timestamp landed in (None for the model's flat price), so callers
    can tell a time-priced row from an ordinary one. rates is that band's own
    per-million table, exactly as stored, so a caller can show which unit
    prices the figure came from instead of re-deriving the band.
    """
    if not row:
        return {"cny": 0.0, "known": False, "band": None, "rates": None}
    pricing = pricing if pricing is not None else load_pricing()
    entry = (pricing.get("models") or {}).get(row.get("model"))
    if not isinstance(entry, dict):
        return {"cny": 0.0, "known": False, "band": None, "rates": None}
    meta = pricing.get("meta") or {}
    unit = _as_float(entry.get("unit")) or 1000000.0
    prompt = _as_float(row.get("prompt_tokens"))
    rate, band, factor = _rate_for(entry, row.get("at"), prompt, meta)
    cached = min(_as_float(row.get("cached_tokens")), prompt)
    uncached = prompt - cached
    # The output rate applies to completion_tokens alone: the upstream counts
    # the reasoning tokens inside completion (verified on live and logged rows,
    # see tests/_test_pricing.py), and so does this gateway when it has to
    # estimate a missing usage block. Billing reasoning_tokens on top would
    # charge them twice.
    output = _as_float(row.get("completion_tokens"))
    miss = _pick(rate, "input_cache_miss")
    hit = _pick(rate, "input_cache_hit", "input_cache_miss")
    out_rate = _pick(rate, "output")
    cny = (uncached * miss + cached * hit + output * out_rate) / unit * factor
    return {"cny": cny, "known": True, "band": band, "rates": rate}


def sum_rows(rows, pricing=None):
    """Batch totals: {"cny", "priced", "missing"}.

    `missing` is model id -> occurrence count for rows the snapshot cannot
    price, so the panel can point at what is not covered instead of quietly
    under-reporting.
    """
    pricing = pricing if pricing is not None else load_pricing()
    total = 0.0
    priced = 0
    missing = {}
    for row in rows or []:
        cost = compute_row(row, pricing=pricing)
        if cost["known"]:
            total += cost["cny"]
            priced += 1
        else:
            mid = str((row or {}).get("model") or "")
            missing[mid] = missing.get(mid, 0) + 1
    return {"cny": total, "priced": priced, "missing": missing}


def usd_cny():
    """The snapshot's CNY-per-USD rate, for callers that show USD."""
    try:
        return float((load_pricing().get("meta") or {}).get("usd_cny") or 1.0)
    except (TypeError, ValueError):
        return 1.0


# ---- snapshot fetching -------------------------------------------------------
# One code path, shared by the CLI refresher (_fetch_pricing.py) and the
# in-process one below, so the two cannot drift apart.

OPENROUTER_URL = "https://openrouter.ai/api/v1/models"
USD_CNY = 7.10

# The realms whose live catalogue feeds the price input beyond the bundled
# snapshot. fetch_remote_product_config() fetches per realm (it knows only
# intl/cn), so both are asked: a model the picker offers on either tab must
# be priced without a release.
LIVE_CATALOG_REALMS = ("intl", "cn")

# Names that differ from OpenRouter's, so the automatic matcher cannot find
# them. Kept deliberately short: a model that matches by name must not be
# listed here, or this becomes the maintenance burden it replaced.
OVERRIDES = {
    # hub 名字比 OpenRouter 多/少一个后缀
    "hy4-preview-f": "tencent/hy4-preview",
    "hy4-preview-dev": "tencent/hy4-preview",
    "hy4-preview-x": "tencent/hy4-preview",
    "hy3-x": "tencent/hy3",
    "kimi-k3-1": "moonshotai/kimi-k3",
    "kimi-k2.7": "moonshotai/kimi-k2.7-code",
    # hub 名字与 OpenRouter 的写法不同（版本号/代号差异）
    "glm-5.0-turbo": "z-ai/glm-5-turbo",
    "deepseek-v3-1": "deepseek/deepseek-chat-v3.1",
    "deepseek-v3-1-volc": "deepseek/deepseek-chat-v3.1",
    "deepseek-v3-2-volc": "deepseek/deepseek-v3.2",
    "deepseek-v3-0324": "deepseek/deepseek-chat-v3-0324",
    # 混元系列在 OpenRouter 上是 a13b-instruct 这一个条目
    "hunyuan-2.0-instruct": "tencent/hunyuan-a13b-instruct",
    "hunyuan-chat": "tencent/hunyuan-a13b-instruct",
}

# 变体后缀表：hub 的名字有时在上游同一实体模型后多带一个渠道/发行后缀。
# 剥掉后缀后按基名重走完整解析链（面板手填覆盖 → 源码覆盖表 → 归一化全等
# 唯一），仍然要求唯一命中，否则照旧算未定价。第二列是该后缀是否参与自动
# 剥离——只放实测确认「同名字后缀 = 同一实体」的那些：
#
#   -lkeap       渠道后缀：实测 deepseek-r1-0528-lkeap / deepseek-v3-1-lkeap /
#                deepseek-v3-0324-lkeap 都能落到同名基准（后两个经 OVERRIDES）
#   -taiji       发行后缀：kimi-k2-instruct-taiji 剥掉后 OR 仍无同名基准，
#                因此照样未定价——把「命不中就不定价」这条规则也钉住
#   -volc        渠道后缀（火山）：deepseek-v3-*-volc 在 OVERRIDES 里已有更
#                精确的写法，这里兜底未来新增的 -volc 变体
#   -sg          节点后缀（新加坡）：同上，剥掉后仍要求唯一命中
#   -f           不剥离：hub 用它区分免费档与付费档，上游 curation 也把它当
#                独立档位；自动继承会抹掉这层语义
#   -dev         不剥离：hub 的预览档后缀（目录里当前没有在用），语义是
#                「另一份构建」而非「同一份价」
#   -x           不剥离：hub 的加量档，实测 hy3-x 与 hy3 单价不同，继承会把
#                价压低
#
# 关闭开关（设置 → 定价刷新 → 变体后缀继承）后，本表整体不参与解析。
VARIANT_SUFFIXES = (
    ("-lkeap", True),
    ("-taiji", True),
    ("-volc", True),
    ("-sg", True),
    ("-f", False),
    ("-dev", False),
    ("-x", False),
)

# 面板手填覆盖的路径由 data_dir() 决定，见 runtime_overrides()。

# OpenRouter 用 UTC 星期名与 HHMM 表达时段档位。
WEEKDAY_KEYS = ("monday", "tuesday", "wednesday", "thursday", "friday",
                "saturday", "sunday")
WEEKDAY_SHORT = ("mon", "tue", "wed", "thu", "fri", "sat", "sun")

_NOTE = ("单价均为「每百万 token」的美元价，取自 OpenRouter 公布的模型级价"
         "（同一模型可能由多家 provider 承接，取它默认路由那家的公布价，"
         "不是各家最低价）；按 usd_cny 折算成人民币；按条件定价的模型"
         "（输入长度阈值或 UTC 时段）另带 bands，按每条请求的输入长度与"
         "时间取档。OpenRouter 的缓存写入价与音频价，本地 usage 日志没有"
         "对应的 token 数，未计入。")


def per_million(value):
    """OpenRouter 的单价是「每 token 的美元」，转成「每百万 token」。"""
    try:
        return round(float(value) * 1_000_000, 6)
    except (TypeError, ValueError):
        return None


def rates_from(item):
    """一条 OpenRouter 记录 → 每百万 token 的三档美元价。"""
    return {
        "input_cache_hit": per_million(item.get("input_cache_read")),
        "input_cache_miss": per_million(item.get("prompt")),
        "output": per_million(item.get("completion")),
    }


def bands_from_overrides(or_entry):
    """条件档位列表；没有条件定价的模型返回空列表。

    OpenRouter 用 overrides 表达两种条件价：

      - min_prompt_tokens：输入长度达到该阈值后改用的价；
      - utc_days / utc_start / utc_end：按时段（UTC）改用的价，
        start / end 是 HHMM 整数（1600 = 16:00），0 作为终点表示当天结束。

    两种条件在源数据里互不混用。档位按源数组的顺序保留，因为计价时取的是
    「最后一条满足条件的档」——这正是源数据的语义：长度档按阈值升序排列
    （实测 32000 → 128000），时段档则互不重叠。与基准价重复、不带任何
    条件的项不取。

    overrides 里还有 input_cache_write / audio / input_audio_cache 这几个
    字段，本地 usage 日志不含对应的 token 数（只有 prompt / completion /
    reasoning / cached），计不出价，所以这里不取。
    """
    out = []
    for item in or_entry.get("overrides") or []:
        if not isinstance(item, dict):
            continue
        band = {"flat": rates_from(item)}
        threshold = item.get("min_prompt_tokens")
        if threshold is not None:
            band["min_prompt_tokens"] = int(threshold)
        elif any(str(k).startswith("utc_") for k in item):
            days = item.get("utc_days")
            picked = [WEEKDAY_SHORT[WEEKDAY_KEYS.index(str(d).lower())]
                      for d in (days if isinstance(days, list) else [])
                      if str(d).lower() in WEEKDAY_KEYS]
            end = item.get("utc_end")
            band.update({
                "days": picked or None,
                "start": int(item.get("utc_start") or 0),
                "end": int(end) if end else 2400,
            })
        else:
            continue
        out.append(band)
    return out


def fetch_openrouter():
    """拉取 OpenRouter 模型列表，返回 {id: pricing}。

    网络失败时抛异常，由调用方决定是记一版失败还是沿用旧价。
    """
    req = urllib.request.Request(
        OPENROUTER_URL, headers={"User-Agent": "workbuddy2api-hub-pricing/1.0"})
    with urllib.request.urlopen(req, timeout=45) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    return {m.get("id"): (m.get("pricing") or {})
            for m in payload.get("data", [])}


def hub_model_ids():
    """内置目录里的模型 id（国际版在前，保序去重）——取价的静态基线。

    目录里新增模型后，这里就会多一个候选；非 chat 的档位别名（
    default-model 等）在 OpenRouter 里匹配不到，自然落进未定价清单。
    本函数语义固定为「静态快照」；运行时取价还会并上网关 live 目录里
    的新增模型，见 priced_model_ids()。
    """
    import wb_catalog
    ids, seen = [], set()
    for source in (getattr(wb_catalog, "STATIC_INTL_MODELS", []),
                   getattr(wb_catalog, "STATIC_CN_MODELS", [])):
        for item in source or []:
            mid = str(item.get("id") or "").strip()
            if mid and mid not in seen:
                seen.add(mid)
                ids.append(mid)
    return ids


def priced_model_ids(extra_ids=None):
    """取价输入清单：静态目录 ∪ 额外 id（去重保序，静态在前）。

    extra_ids 是网关 live 目录里新增、静态快照还没有的模型，由调用方按
    /v1/models 的同一套过滤整理好（见 PriceRefresher._live_ids）。别名不会
    从这里进来：curate_remote_catalog 已把 default-model 一类剔除；静态
    目录里本来就有别名，它们匹配不到 OpenRouter，被算作未定价但不计缺口。
    """
    ids, seen = [], set()
    for mid in hub_model_ids():
        if mid not in seen:
            seen.add(mid)
            ids.append(mid)
    for raw in extra_ids or []:
        mid = str(raw or "").strip()
        if mid and mid not in seen:
            seen.add(mid)
            ids.append(mid)
    return ids


# ---- variant inheritance -----------------------------------------------------
# hub 的新模型常带着渠道/发行后缀（-lkeap、-taiji ...），名字对不上任何
# OpenRouter 条目时，按 VARIANT_SUFFIXES 剥掉后缀、拿基名重走解析链。继承
# 来的价在策略里留 via / inherited_from，面板能看出它不来自同名条目。

_settings_dir_override = None
# 开关本身几乎不变，但 ensure_policy 会在每次「这个模型还没有价」的请求上走到
# 这里；按 (path, mtime, size) 缓存一次，省掉热路径上的 settings.json 解析。
_variant_cache = {"key": None, "value": True}
_variant_lock = threading.Lock()
# 总开关走同一套缓存：请求路径上每一行都要问一次「价估算开着吗」，更不能
# 每次去解析 settings.json。
_enabled_cache = {"key": None, "value": True}
_enabled_lock = threading.Lock()


def set_settings_dir(path):
    """wb_proxy 指向自己的 accounts 目录，让开关与面板读写同一份设置。"""
    global _settings_dir_override
    _settings_dir_override = path


# 请求路径上每一行都要问一次总开关，而 settings_path 每次都要把固定文件名
# join 到 accounts 目录上——现场那份逐行剖面里 os.path.join 排第二，其中约
# 三分之一就是这里。它只是一次 join，同一个目录永远给同一个字符串，所以按
# 目录缓存一次即可：目录变了键就变，不需要别的失效条件。
_settings_path_cache = {}
_MEMO_LIMIT = 512


def _memo_put(cache, key, value):
    """写一个小的派生值缓存（按对象身份或按目录字符串做键），超上限就整体清空。

    只放由对象内容决定的派生值，所以清空只会让下一次多算一遍，正确性不依赖
    任何驱逐策略；并发下最坏是两个线程各算一遍，交回的是等价的两份。
    """
    if len(cache) > _MEMO_LIMIT:
        cache.clear()
    cache[key] = value


def _cached_switch(cache, lock, reader, accounts_dir, default):
    """读一个存在 settings.json 里的开关，按 (path, mtime, size) 缓存。

    面板改设置会改 mtime，缓存自然失效；任何异常都退回 default，坏掉的
    settings.json 不能把取价或请求路径带崩。
    """
    try:
        import wb_settings
        path = accounts_dir or _settings_dir_override or os.environ.get("ACCOUNTS_DIR")
        if not path:
            return default
        try:
            settings = _settings_path_cache.get(path)
            if settings is None:
                settings = wb_settings.settings_path(path)
                _memo_put(_settings_path_cache, path, settings)
            # 一次 stat 同时取 mtime 和 size：请求路径上每一行都要问一次这个
            # 开关，getmtime + getsize 是两次系统调用。缓存键与原来完全一致
            # （getmtime/getsize 就是 st_mtime/st_size），所以外部改设置仍然
            # 当场可见——这个开关不能有 TTL。
            info = os.stat(settings)
            key = (settings, info.st_mtime, info.st_size)
        except OSError:
            key = (path, None, None)
        with lock:
            if cache["key"] == key:
                return cache["value"]
        value = reader(path)
        with lock:
            cache.update({"key": key, "value": value})
        return value
    except Exception:
        return default


def variant_inherit_enabled(accounts_dir=None):
    """变体后缀继承是否打开。默认打开；读不到设置也不影响取价。"""
    import wb_settings
    return _cached_switch(_variant_cache, _variant_lock,
                          wb_settings.pricing_variant_inherit, accounts_dir, True)


def pricing_enabled(accounts_dir=None):
    """价估算总开关是否打开。默认打开；读不到设置按打开处理。"""
    import wb_settings
    return _cached_switch(_enabled_cache, _enabled_lock,
                          wb_settings.pricing_enabled, accounts_dir, True)


def variant_bases(hub_id):
    """去掉变体后缀后的候选基名，按表内顺序；没启用剥离时为空。"""
    name = str(hub_id or "").strip()
    for suffix, enabled in VARIANT_SUFFIXES:
        if not enabled or not name.endswith(suffix):
            continue
        base = name[:-len(suffix)].strip()
        if base:
            yield base


def normalize(name):
    """名字归一化：小写、去掉所有非字母数字（- . _ 等一律忽略）。"""
    return re.sub(r"[^a-z0-9]", "", str(name or "").lower())


def index_openrouter(or_models):
    """按归一化名字建索引，排除 :batch / :free 等变体。"""
    by_norm = {}
    for mid in or_models or {}:
        if ":" in mid:
            continue
        by_norm.setdefault(normalize(mid.split("/")[-1]), []).append(mid)
    return by_norm


def auto_match(hub_id, by_norm):
    """名字归一化后全等且唯一才返回，否则 None——宁可漏也不错。"""
    cands = by_norm.get(normalize(str(hub_id).split("/")[-1])) or []
    return cands[0] if len(cands) == 1 else None


def _resolve_once(hub_id, or_models, by_norm):
    """面板手填覆盖 → 源码覆盖表 → 归一化全等唯一，三层解析一次。"""
    for table in (runtime_overrides(), OVERRIDES):
        ref = table.get(hub_id)
        if ref and ref in or_models:
            return ref, True
    auto = auto_match(hub_id, by_norm)
    return (auto, False) if auto else (None, False)


def resolve(hub_id, or_models, by_norm, variants=None):
    """(OpenRouter id, 是否来自人工覆盖)；匹配不到返回 (None, False)。

    variants 为 None 时读设置开关（默认开）。剥后缀继承来的命中一律记作
    人工覆盖，因为那不是名字碰巧相同，而是一次有据可查的判定。
    """
    if variants is None:
        variants = variant_inherit_enabled()
    ref, via_override = _resolve_once(hub_id, or_models, by_norm)
    if ref or not variants:
        return ref, via_override
    for base in variant_bases(hub_id):
        ref, via_override = _resolve_once(base, or_models, by_norm)
        if ref:
            return ref, True
    return None, False


def inherited_from(hub_id, or_models, by_norm):
    """这条命中是不是剥后缀继承来的；是则返回基准模型名，否则 None。"""
    if _resolve_once(hub_id, or_models, by_norm)[0]:
        return None
    for base in variant_bases(hub_id):
        if _resolve_once(base, or_models, by_norm)[0]:
            return base
    return None


def entry_for(hub_id, ref, or_models, inherited=None, overridden=False):
    """一条 hub 模型 → OpenRouter 条目的快照记录（刷新与按需补价共用）。

    inherited 非空时是剥后缀继承来的基准模型名，写进 via / inherited_from；
    overridden 表示这次命中来自人工映射表（面板手填或 OVERRIDES），写进
    via="override" 与 override_from。resolve() 的变体分支同样返回
    via_override=True，所以两个分支必须靠 inherited 区分，否则变体继承会被
    误记成人工映射。这三个字段都不参与 policy_id 的内容哈希，只作展示与追溯。
    """
    p = or_models.get(ref) or {}
    entry = {
        "display": hub_id,
        "source": "openrouter",
        "currency": "USD",
        "unit": 1_000_000,
        "or_id": ref,
        "flat": rates_from(p),
    }
    bands = bands_from_overrides(p)
    if bands:
        entry["bands"] = bands
    if inherited:
        entry["via"] = "variant"
        entry["inherited_from"] = inherited
    elif overridden:
        entry["via"] = "override"
        entry["override_from"] = hub_id
    return entry


def build_snapshot(or_models, previous=None, extra_ids=None, variants=None):
    """(doc, unpriced, overridden)。

    or_models 为 None 表示这次抓取失败：结果沿用 previous 里的价（没有就
    留空），这样一次网络抖动不会把价格表清掉。

    extra_ids 是要额外覆盖的模型（网关 live 目录里新增、静态快照还没有
    的那些），与静态目录取并集后一起解析，去重保序。variants 覆盖变体继
    承开关（None = 读设置，默认开）。
    """
    if variants is None:
        variants = variant_inherit_enabled()
    by_norm = index_openrouter(or_models) if or_models else {}
    models, unpriced, overridden = {}, [], []
    for hub_id in priced_model_ids(extra_ids):
        if or_models is None:
            old = (previous or {}).get(hub_id)
            if old:
                models[hub_id] = old
            else:
                unpriced.append(hub_id)
            continue
        ref, via_override = resolve(hub_id, or_models, by_norm, variants=variants)
        if not ref:
            unpriced.append(hub_id)
            continue
        if via_override:
            overridden.append(hub_id)
        models[hub_id] = entry_for(
            hub_id, ref, or_models,
            inherited=(inherited_from(hub_id, or_models, by_norm)
                       if variants else None),
            overridden=via_override)
    doc = {
        "meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "base_currency": "CNY",
            "usd_cny": USD_CNY,
            "sources": {"openrouter": OPENROUTER_URL},
            "note": _NOTE,
        },
        "models": models,
    }
    return doc, unpriced, overridden


# ---- price policies ----------------------------------------------------------
# A price is stored once per (model, rates) pair, keyed by a hash of its own
# content, and a timeline records which policy each model was on at any moment.
# Re-fetching a price that has been seen before reuses the existing row instead
# of writing a new one, so a vendor flipping A -> B -> A costs two rows rather
# than three. A request stores the *reference* to the policy that priced it, not
# a copy of the rates, which is what lets an unreferenced policy be dropped.

_policy_lock = threading.RLock()
_policies_cache = {"key": None, "data": None}
_timeline_cache = {"key": None, "data": None}
_data_dir_override = None


def data_dir():
    """Where the policy files live: the usage folder by default."""
    if _data_dir_override:
        return _data_dir_override
    env = os.environ.get("WB_PRICING_DIR")
    if env:
        return env
    usage = os.environ.get("WB_PROXY_USAGE_DIR")
    return usage or os.path.join(os.path.dirname(os.path.abspath(__file__)), "usage")


def set_data_dir(path):
    """wb_proxy points this at its own data dir so both sides agree."""
    global _data_dir_override
    with _policy_lock:
        _data_dir_override = path
        _policies_cache.update({"key": None, "data": None})
        _timeline_cache.update({"key": None, "data": None})


# 聚合一份两万行的日志时，每一行都要问几次「策略表 / 时间线 / 覆盖表在哪」，
# 每个问题都是一次 os.path.join，而数据目录在一次聚合里根本不会变。四个派生
# 路径按目录字符串缓存——键就是 data_dir() 本身，所以目录一变（面板换数据
# 目录、测试里每个用例一个临时目录）自然落到新键上，返回的字符串与逐个
# os.path.join 拼出来的完全一致。
_paths_cache = {}


def _data_paths():
    """(策略表, 时间线, usage 日志, 覆盖表) —— 当前数据目录下的四个路径。"""
    base = data_dir()
    hit = _paths_cache.get(base)
    if hit is not None:
        return hit
    hit = (os.path.join(base, "pricing-policies.jsonl"),
           os.path.join(base, "pricing-timeline.jsonl"),
           os.path.join(base, "usage.jsonl"),
           os.path.join(base, "pricing-overrides.json"))
    _memo_put(_paths_cache, base, hit)
    return hit


def policies_path():
    return _data_paths()[0]


def timeline_path():
    return _data_paths()[1]


def usage_log_path():
    """The usage log, which wb_proxy keeps in the same folder."""
    return _data_paths()[2]


def overrides_path():
    """面板手填的 hub → OpenRouter id 映射文件。

    与源码里的 OVERRIDES 分开：面板写的是运行期覆盖，落在 usage/ 数据目录
    里，升级镜像不会丢，也不会被镜像覆盖。
    """
    return _data_paths()[3]


_runtime_overrides_cache = {"key": None, "data": {}}


def _read_runtime_overrides():
    """The file's content, ignoring nothing but a missing/corrupt file."""
    data = {}
    try:
        with open(overrides_path(), encoding="utf-8") as fh:
            loaded = json.load(fh)
        if isinstance(loaded, dict):
            for mid, ref in loaded.items():
                mid, ref = str(mid or "").strip(), str(ref or "").strip()
                if mid and ref:
                    data[mid] = ref
    except Exception:
        data = {}
    return data


def runtime_overrides():
    """{hub id: OpenRouter id}——面板手填、按 mtime 缓存的覆盖映射。"""
    path = overrides_path()
    try:
        key = (path, os.path.getmtime(path), os.path.getsize(path))
    except OSError:
        return {}
    with _policy_lock:
        if _runtime_overrides_cache["key"] == key:
            return _runtime_overrides_cache["data"]
    data = _read_runtime_overrides()
    with _policy_lock:
        _runtime_overrides_cache.update({"key": key, "data": data})
    return data


def save_runtime_override(model, or_id):
    """写入/清除一条面板手填映射；返回写后的整份映射。

    or_id 为空表示删除这条映射（回到源码覆盖表与自动匹配）。
    """
    model = str(model or "").strip()
    or_id = str(or_id or "").strip()
    path = overrides_path()
    with _policy_lock:
        data = _read_runtime_overrides()
        if or_id:
            data[model] = or_id
        else:
            data.pop(model, None)
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=2, sort_keys=True)
        os.replace(tmp, path)
        _runtime_overrides_cache.update({"key": None, "data": data})
    return data


# 仪表盘聚合整份 usage 日志时，每一行都要问一次「策略表 / 时间线文件变了
# 吗」，一次询问就是一次 stat——路由器上这是这趟扫描最大的一项开销。答案按
# 路径缓存一个很短的 TTL：本进程之外写下的变更最迟 _FILE_KEY_TTL 秒内一定
# 被看见（一次聚合里 stat 从每行数次降到每秒一次），而本进程自己的写入立刻
# 作废缓存（见 _forget_file_key），所以「刚记完价的那一行」一行都不等。
_FILE_KEY_TTL = 1.0
_file_key_cache = {}
_file_key_lock = threading.Lock()


def _forget_file_key(path):
    """作废一个本进程刚写过的文件的 stat 缓存。

    写入方在写完之后立刻调用，把「自己写的变更」从 TTL 里摘出来：策略表在
    取价后的下一行就要能被读到，不能等满一个 TTL。
    """
    with _file_key_lock:
        _file_key_cache.pop(path, None)


def _file_key(path):
    """(path, mtime, size)，按路径缓存 TTL；取不到时 None。"""
    now = time.monotonic()
    with _file_key_lock:
        hit = _file_key_cache.get(path)
        if hit is not None and hit[0] > now:
            return hit[1]
    try:
        # 一次 stat 同时取 mtime 和 size，比 getmtime + getsize 少一次系统调用。
        info = os.stat(path)
        key = (path, info.st_mtime, info.st_size)
    except OSError:
        key = None
    with _file_key_lock:
        if len(_file_key_cache) > 32:
            # 正常进程里只有数据目录下那两三个文件；这里只为「路径会换」的场合
            # 兜底（换过数据目录、测试里每个用例一个临时目录）。清掉只会让下
            # 一次多 stat 一次，正确性不受任何驱逐策略影响。
            _file_key_cache.clear()
        _file_key_cache[path] = (now + _FILE_KEY_TTL, key)
    return key


def _read_jsonl(path):
    rows = []
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    item = json.loads(line)
                except Exception:
                    continue
                if isinstance(item, dict):
                    rows.append(item)
    except Exception:
        return []
    return rows


def policy_id(model, flat, bands, usd_cny):
    """Content hash: the same model priced the same way gets the same id.

    The rate is part of the hash because it decides the CNY figure just as
    much as the dollar prices do; a rate change is a different policy.
    """
    payload = json.dumps(
        {"model": model, "flat": flat, "bands": bands or None,
         "usd_cny": round(_as_float(usd_cny, 0.0), 6)},
        sort_keys=True, ensure_ascii=False)
    return hashlib.sha1(payload.encode("utf-8")).hexdigest()[:12]


def load_policies():
    """{id: policy} - the policy table, de-duplicated by content."""
    path = policies_path()
    key = _file_key(path)
    if key is None:
        return {}
    with _policy_lock:
        if _policies_cache["key"] == key and _policies_cache["data"] is not None:
            return _policies_cache["data"]
    data = {}
    for row in _read_jsonl(path):
        pid = row.get("id")
        if pid:
            data[pid] = row
    with _policy_lock:
        _policies_cache.update({"key": key, "data": data})
    return data


def load_timeline():
    """[{"at": epoch, "policies": {model: id}}], oldest first."""
    path = timeline_path()
    key = _file_key(path)
    if key is None:
        return []
    with _policy_lock:
        if _timeline_cache["key"] == key and _timeline_cache["data"] is not None:
            return _timeline_cache["data"]
    rows = [r for r in _read_jsonl(path) if isinstance(r.get("policies"), dict)]
    rows.sort(key=lambda r: _as_float(r.get("at")))
    with _policy_lock:
        _timeline_cache.update({"key": key, "data": rows})
    return rows


def current_assignment():
    """(epoch, {model: policy id}) - the timeline's last row, i.e. what is in
    force now. (None, {}) when nothing has been fetched yet.
    """
    timeline = load_timeline()
    if not timeline:
        return None, {}
    last = timeline[-1]
    return _as_float(last.get("at")), dict(last.get("policies") or {})


def current_policy_id(model):
    """The policy in force for this model, for wb_proxy to stamp on a row.

    A model with no policy yet is priced on demand from the OpenRouter index
    the last fetch left in memory (never from the network - the request path
    must not block on a fetch), so a model first called between two refreshes
    still carries its price. A miss stays a miss and the row is stamped
    without a reference, exactly as before.

    With the master switch off nothing is priced at all, so no reference is
    stamped and no on-demand policy is minted.
    """
    if not pricing_enabled():
        return None
    _at, assignment = current_assignment()
    pid = assignment.get(model)
    if pid:
        return pid
    return ensure_policy(model)


# ---- on-demand pricing -------------------------------------------------------
# The refresher keeps the last successful OpenRouter reading in memory. A model
# that appears in it but has no policy yet - the upstream added it and the
# gateway is called before the next cycle - is priced from that index right
# when the request is logged, so the first row already carries a price.

_live_lock = threading.Lock()
_live_index = {"models": None, "by_norm": None, "at": None}


def remember_live_index(or_models):
    """Remember a successful fetch for the on-demand path (memory only).

    A failed fetch never calls this, so the last good reading stays usable.
    """
    if not or_models:
        return
    by_norm = index_openrouter(or_models)
    with _live_lock:
        _live_index.update({"models": dict(or_models), "by_norm": by_norm,
                            "at": time.time()})


def live_index():
    """(or_models, by_norm) from the last successful fetch; (None, {}) if none."""
    with _live_lock:
        return _live_index["models"], (_live_index["by_norm"] or {})


# ---- gateway interop ---------------------------------------------------------
# The gateway is usually imported, but the container starts it as a script
# (`python wb_proxy.py`), which makes the running instance __main__. A plain
# `import wb_proxy` would then execute the file a second time inside the same
# process, and that twin has no account pool - so the live catalogue quietly
# reads as empty - plus its own log buffer, so pricing lines never reach the
# panel. Both were observed in production, so resolve the module that is
# actually running; only fall back to a fresh import when none is loaded.

def gateway_module():
    """The live gateway module (or a fresh import when nothing is loaded)."""
    main = sys.modules.get("__main__")
    if main is not None and hasattr(main, "curated_live_sources"):
        return main
    module = sys.modules.get("wb_proxy")
    if module is not None:
        return module
    import wb_proxy as module
    return module


def _log_pricing(msg):
    """Mirror a line into the gateway log; pricing must not depend on it."""
    try:
        gateway_module().add_log_entry("[定价] %s" % msg, tag="pricing")
    except Exception:
        pass


def ensure_policy(model):
    """Register a policy for a model that has none, from the in-memory index.

    Returns the policy id, or None when the index is cold, the name does not
    resolve, or anything goes wrong - the caller then treats the row as
    unpriced, which is the same answer as before this path existed. Never
    touches the network, and repeated calls are idempotent because policies
    are keyed by a content hash; only a genuinely new policy logs a line.

    The master switch short-circuits this too: with pricing off, no policy is
    minted and nothing is written to the policy table.
    """
    if not pricing_enabled():
        return None
    mid = str(model or "").strip()
    if not mid:
        return None
    or_models, by_norm = live_index()
    if not or_models:
        return None
    try:
        inherited = inherited_from(mid, or_models, by_norm)
        ref, via = resolve(mid, or_models, by_norm)
        if not ref:
            return None
        entry = entry_for(mid, ref, or_models, inherited=inherited,
                          overridden=via)
        doc = {"meta": {"base_currency": "CNY", "usd_cny": USD_CNY},
               "models": {mid: entry}}
        added, _changed, assignment = record_policies(doc, merge=True)
        pid = assignment.get(mid)
        if added:
            _log_pricing("按需补价：%s → %s%s（策略 %s）"
                         % (mid, ref,
                            "（继承自 %s）" % inherited if inherited
                            else ("（人工映射）" if via else ""), pid))
        return pid
    except Exception as exc:
        _log_pricing("按需补价失败（按未定价处理）：%s（%s）" % (mid, exc))
        return None


# ---- unpriced visibility -----------------------------------------------------
# The panel has to be able to answer "which models would show a dash, and why"
# instead of hiding that in the refresh log. Candidates are suggestions only -
# nothing here changes a price.

_ALIAS_FALLBACK = ("default-model", "fast-model", "balanced-model",
                   "primary-model", "deep-model", "auto")


def virtual_alias_names():
    """The virtual-alias set (non-models). Read from the gateway when importable
    so the two sides cannot drift; a local fallback keeps this usable alone."""
    try:
        names = getattr(gateway_module(), "VIRTUAL_ALIAS_MODELS", None)
        if names:
            return {str(n) for n in names}
    except Exception:
        pass
    return set(_ALIAS_FALLBACK)


def suggest_matches(hub_id, or_models, limit=3):
    """Top OpenRouter ids that look like `hub_id` - suggestions, never applied.

    Substring containment on the normalized names first (cheap and the way a
    channel suffix usually shows up), then edit-distance ratio for the rest.
    """
    target = normalize(hub_id)
    if len(target) < 3 or not or_models:
        return []
    scored = []
    for mid in or_models:
        if ":" in mid:
            continue
        leaf = normalize(mid.split("/")[-1])
        if not leaf:
            continue
        if leaf in target or target in leaf:
            score = 0.75 + 0.25 * min(len(leaf), len(target)) / max(len(leaf), len(target))
        else:
            score = _ratio(target, leaf)
        if score >= 0.6:
            scored.append((score, mid))
    scored.sort(key=lambda item: (-item[0], item[1]))
    return [mid for _score, mid in scored[:limit]]


def _ratio(a, b):
    """SequenceMatcher ratio with a cheap length filter in front."""
    if not a or not b:
        return 0.0
    if abs(len(a) - len(b)) > max(len(a), len(b)) * 0.6:
        return 0.0
    import difflib
    return difflib.SequenceMatcher(None, a, b).ratio()


def gap_items(or_models, by_norm=None, extra_ids=None, variants=None, priced=()):
    """(items, summary) - unpriced models, categorised, with suggestions.

    A model counts as priced when a live/factory price covers it or the
    in-memory index resolves it (the on-demand path would price it on first
    use). What remains is a lasting gap and is reported:

      - alias: a virtual entry (default-model ...), not a model at all; it is
        not part of the gap count the panel shows;
      - variant_unmatched: the name carries a variant suffix from the table,
        but even the stripped base name matches nothing (or nothing unique);
      - or_missing: OpenRouter lists no counterpart - the operator can map one
        by hand from the panel, which is what the candidates are for.

    Rows for aliases carry no candidates: there is nothing to map them to.
    """
    if variants is None:
        variants = variant_inherit_enabled()
    by_norm = by_norm if by_norm is not None else index_openrouter(or_models)
    aliases = virtual_alias_names()
    known = set(priced or ()) | set((load_pricing().get("models") or {}))
    items, counts = [], {"alias": 0, "or_missing": 0, "variant_unmatched": 0}
    for mid in priced_model_ids(extra_ids):
        if mid in known:
            continue
        if or_models and resolve(mid, or_models, by_norm, variants=variants)[0]:
            continue
        if mid in aliases:
            reason = "alias"
        elif any(True for _ in variant_bases(mid)):
            reason = "variant_unmatched"
        else:
            reason = "or_missing"
        counts[reason] += 1
        item = {"model": mid, "reason": reason}
        if reason != "alias":
            item["candidates"] = suggest_matches(mid, or_models)
        items.append(item)
    summary = {
        "total": counts["or_missing"] + counts["variant_unmatched"],
        "or_missing": counts["or_missing"],
        "variant_unmatched": counts["variant_unmatched"],
        "aliases": counts["alias"],
        "variants_enabled": bool(variants),
    }
    return items, summary


# 一份两万行的日志里，同一个策略要被 policy_entry 重建上万次，而它只由策略行
# 自己的内容决定，一次都不会变（cost_for_row 自己一次、_details_for 再一次，
# 现场是每行两次）。按策略对象的身份缓存：策略表刷新后 load_policies 重读文件
# 交回的是全新的行对象，键自然不同，旧缓存再也命中不到；缓存里同时握着策略
# 对象本身，所以身份不可能在对象被回收后被复用（命中时还会再确认一次）。
# 缓存的 entry 只被 compute_row 与 _details_for 读，从不交给调用方，也没有人
# 改它（rates 由 _details_for 另拷一份），所以外面看到的还是各自独立的 dict。
_entry_memo = {}


def policy_entry(policy):
    """A policy record turned back into the entry the cost engine expects."""
    key = id(policy)
    hit = _entry_memo.get(key)
    if hit is not None and hit[0] is policy:
        return hit[1]
    entry = {
        "display": policy.get("model"),
        "source": "openrouter",
        "currency": policy.get("currency") or "USD",
        "unit": policy.get("unit") or 1000000,
        "or_id": policy.get("or_id"),
        "flat": policy.get("flat") or {},
        # 展示字段，与 entry_for 写进快照的同一套；老策略行没有这几个键，
        # cost_for_row 会用当前映射表去解释。
        "via": policy.get("via"),
        "inherited_from": policy.get("inherited_from"),
        "override_from": policy.get("override_from"),
    }
    if policy.get("bands"):
        entry["bands"] = policy["bands"]
    _memo_put(_entry_memo, key, (policy, entry))
    return entry


def _doc_for(policy, model):
    return {
        "meta": {"base_currency": "CNY",
                 "usd_cny": _as_float(policy.get("usd_cny"), USD_CNY)},
        "models": {model: policy_entry(policy)},
    }


def record_policies(doc, at=None, merge=False):
    """Register a fetched snapshot: table first, then the timeline.

    Returns (new policies, timeline appended, {model: id}). A price that is
    already in the table is not written again, and the timeline only grows
    when the assignment actually changes - so a steady price costs nothing per
    refresh no matter how often it is checked.

    merge=True starts the timeline row from the assignment already in force
    and overlays this doc, instead of replacing it. One on-demand
    registration - a single model, recorded between two fetches - must not
    make the panel's "in force now" view drop every other model.

    The whole read-decide-append runs under one (reentrant) lock: two threads
    pricing the same new model at once must append its policy row once, and
    the timeline row they would both write must be written once.
    """
    stamp = time.time() if at is None else _as_float(at)
    models = doc.get("models") or {}
    usd = _as_float((doc.get("meta") or {}).get("usd_cny"), USD_CNY)
    with _policy_lock:
        known = load_policies()
        fresh, assignment = [], {}
        _previous_at, previous = current_assignment()
        if merge:
            assignment = dict(previous)
        for model, entry in models.items():
            pid = policy_id(model, entry.get("flat"), entry.get("bands"), usd)
            assignment[model] = pid
            if pid in known:
                continue
            known[pid] = {
                "id": pid,
                "model": model,
                "or_id": entry.get("or_id"),
                "currency": entry.get("currency") or "USD",
                "unit": entry.get("unit") or 1000000,
                "usd_cny": usd,
                "flat": entry.get("flat") or {},
                "bands": entry.get("bands"),
                # 审计痕迹：这条价是直接匹配、人工映射还是从基准模型继承来的
                # （via="variant" 时 inherited_from 给出基准名，via="override"
                # 时 override_from 给出原始 hub 模型名）。不进哈希。
                "via": entry.get("via") or "direct",
                "inherited_from": entry.get("inherited_from"),
                "override_from": entry.get("override_from"),
                "first_seen": stamp,
            }
            fresh.append(known[pid])
        if fresh:
            path = policies_path()
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            with open(path, "a", encoding="utf-8") as fh:
                for row in fresh:
                    fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            _policies_cache.update({"key": None, "data": None})
            _forget_file_key(path)
        changed = False
        if assignment and assignment != previous:
            path = timeline_path()
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            with open(path, "a", encoding="utf-8") as fh:
                fh.write(json.dumps({"at": stamp, "policies": assignment},
                                    ensure_ascii=False) + "\n")
            _timeline_cache.update({"key": None, "data": None})
            _forget_file_key(path)
            changed = True
    return len(fresh), changed, assignment


def referenced_policy_ids():
    """The policy ids any usage row points at."""
    ids = set()
    try:
        with open(usage_log_path(), encoding="utf-8") as fh:
            for line in fh:
                if '"cost_policy"' not in line:
                    continue
                try:
                    row = json.loads(line)
                except Exception:
                    continue
                pid = row.get("cost_policy")
                if pid:
                    ids.add(pid)
    except Exception:
        return set()
    return ids


def prune_policies(protect=()):
    """Drop the policies nothing points at.

    Kept are the models' current assignment, every id a usage row references,
    whatever the caller pins (the batch just fetched), and - so no model is
    ever left with nothing to price it by - the newest policy of a model that
    would otherwise lose its last row. Returns the removed ids.
    """
    policies = load_policies()
    if not policies:
        return []
    _at, assignment = current_assignment()
    keep = set(assignment.values()) | set(referenced_policy_ids()) | set(protect)
    by_model = {}
    for pid, policy in policies.items():
        by_model.setdefault(policy.get("model"), []).append(pid)
    for ids in by_model.values():
        if any(pid in keep for pid in ids):
            continue
        newest = max(ids, key=lambda p: _as_float((policies[p] or {}).get("first_seen")))
        keep.add(newest)
    removed = [pid for pid in policies if pid not in keep]
    if not removed:
        return []
    path = policies_path()
    tmp = path + ".tmp"
    with _policy_lock:
        with open(tmp, "w", encoding="utf-8") as fh:
            for pid, policy in policies.items():
                if pid in keep:
                    fh.write(json.dumps(policy, ensure_ascii=False) + "\n")
        os.replace(tmp, path)
        _policies_cache.update({"key": None, "data": None})
        _forget_file_key(path)
    return removed


# load_timeline() 对同一份文件内容交回的是同一个列表对象，所以「是不是同一份
# 时间线」直接用对象身份判断即可。policy_ref_at 每行都要二分一次，而每行把整条
# 时间线的 at 重新取一遍再转 float 是白花的（现场 46 行 × 每行一次，实测是聚合
# 里可观的一块）；时刻列随列表一起缓存，改文件后 load_timeline 交回新对象，
# 这里自然重算。
_timeline_ats_cache = {"rows": None, "ats": None}


def _timeline_ats(timeline):
    """这条时间线的时刻列，随它自己的对象缓存一次。"""
    cached = _timeline_ats_cache
    if cached["rows"] is timeline:
        return cached["ats"]
    ats = [_as_float(r.get("at")) for r in timeline]
    with _policy_lock:
        _timeline_ats_cache.update({"rows": timeline, "ats": ats})
    return ats


def policy_ref_at(epoch_sec, model):
    """(policy id, backfilled) - which policy a moment in the past should use.

    - the last timeline row at or before the moment, if it lists this model;
    - otherwise the first *later* row that lists it, which is the "the price
      was only learned after the fact" case, marked as backfilled;
    - failing that, an earlier row, also marked, for a model that was dropped;
    - an empty timeline yields (None, False) and the caller falls back to the
      factory snapshot.
    """
    timeline = load_timeline()
    if not timeline:
        return None, False
    stamp = _as_float(epoch_sec)
    index = bisect.bisect_right(_timeline_ats(timeline), stamp) - 1
    if index < 0:
        index = 0
    rows = timeline[index].get("policies") or {}
    if model in rows:
        return rows[model], False
    for row in timeline:
        if _as_float(row.get("at")) < stamp:
            continue
        hit = (row.get("policies") or {}).get(model)
        if hit:
            return hit, True
    for row in reversed(timeline[:index + 1]):
        hit = (row.get("policies") or {}).get(model)
        if hit:
            return hit, True
    return None, False


# ---- what a row's price is made of -------------------------------------------
# 面板要能回答「这个数是怎么来的」：这条请求落在哪一档、那一档的三档单价是
# 多少、按哪条 OpenRouter 条目、又是怎么匹配到它的。这里把 cost_for_row 已经
# 决定好的东西摊开，不改任何计价口径。

_WEEKDAY_CN = {"mon": "周一", "tue": "周二", "wed": "周三", "thu": "周四",
               "fri": "周五", "sat": "周六", "sun": "周日"}

# 明细字段的固定顺序，未定价时整组给 None，不编 0。
_DETAIL_KEYS = ("rates", "unit", "currency", "usd_cny", "or_id", "via",
                "inherited_from", "override_from", "band_note", "via_derived")


def _hhmm(value):
    """1600 -> 16:00；2400 是源里「当天结束」的写法。"""
    minutes = int(_as_float(value))
    return "%02d:%02d" % (minutes // 100, minutes % 100)


def band_note(entry, index):
    """这一行凭什么落在这个条件档位；没有档位（或索引越界）时 None。"""
    bands = entry.get("bands")
    if index is None or not isinstance(bands, list):
        return None
    if not isinstance(index, int) or not 0 <= index < len(bands):
        return None
    band = bands[index]
    if not isinstance(band, dict):
        return None
    threshold = band.get("min_prompt_tokens")
    if threshold is not None:
        return "输入长度 ≥ %s tokens" % format(int(_as_float(threshold)), ",")
    days = [day for day in (band.get("days") or []) if day in _WEEKDAY_CN]
    window = "%s–%s UTC" % (_hhmm(band.get("start")), _hhmm(band.get("end")))
    if days:
        return "每周 %s %s" % ("/".join(_WEEKDAY_CN[day] for day in days), window)
    return "每天 %s" % window


def match_source(entry, model):
    """(via, inherited_from, override_from, derived) —— 这条价怎么匹配来的。

    策略行里记着 via 就直接用。更早写下的策略行没有这个字段（字段是后加的），
    只能拿当前映射表去解释：模型在表里、且表里指的正是这条 or_id，那它只可能
    是人工映射命中，按 override 记并标记为推断；表改过或指不到这条就不敢这么
    说，按直接匹配记。
    """
    via = str(entry.get("via") or "").strip()
    if via in ("variant", "override", "direct"):
        return via, entry.get("inherited_from"), entry.get("override_from"), False
    mapping = runtime_overrides().get(model) or OVERRIDES.get(model)
    if mapping and mapping == entry.get("or_id"):
        return "override", None, model, True
    return "direct", None, None, False


def _no_details():
    return {key: None for key in _DETAIL_KEYS}


# 明细整块只由 entry、它落在的那一档、meta 和行上的模型名决定——前三个在策略表
# （或出厂快照文件）刷新前一直是同一批对象（策略行的 entry 由 policy_entry 缓存
# 交回，所以同一策略的行拿到的是同一个 entry）。按它们的身份缓存一份模板，
# 命中时只把 rates 拷一份出来：与逐字段重建的结果逐键一致（含键序），而每个
# 调用方拿到的 rates 仍是自己的副本，和从前一样。
#
# 唯一读外部状态的是 match_source 对「没有 via 的老策略行」的推断，那种行的
# 解释会随覆盖表变化，所以它们一次都不进缓存（缓存键里没有覆盖表的状态，
# 也就不可能给出一份过期的解释）；记着 via 的行根本不查覆盖表，缓存才成立。
#
# 键是身份，值里必须同时握着这三个对象：身份只在对象活着的时候唯一，缓存自己
# 拿住引用，键才不会被回收后的新对象复用（这正是策略表刷新时换上的那批新行）。
_details_memo = {}


def _details_for(cost, entry, meta, model):
    """这一行实际用的价摊开：档位说明、三档单价、汇率、匹配来源。"""
    if not cost.get("known") or not isinstance(entry, dict):
        return _no_details()
    rates = cost.get("rates")
    recorded = entry.get("via")
    key = None
    if recorded in ("variant", "override", "direct"):
        key = (id(entry), id(meta), id(rates), cost.get("band"), model)
        hit = _details_memo.get(key)
        if hit is not None:
            # hit 是 (entry, meta, rates, 模板)：模板照抄一份，rates 按源表另拷。
            out = dict(hit[3])
            out["rates"] = dict(hit[2] or {})
            return out
    via, inherited, override_from, derived = match_source(entry, model)
    template = {
        # 源表：交给调用方的那一份在下面另拷，缓存里留的是原对象。
        "rates": rates or {},
        "unit": _as_float(entry.get("unit")) or 1000000.0,
        "currency": entry.get("currency") or "USD",
        "usd_cny": _as_float((meta or {}).get("usd_cny")),
        "or_id": entry.get("or_id"),
        "via": via,
        "inherited_from": inherited,
        "override_from": override_from,
        "band_note": band_note(entry, cost.get("band")),
        "via_derived": derived,
    }
    if key is not None:
        _memo_put(_details_memo, key, (entry, meta, rates, template))
    out = dict(template)
    out["rates"] = dict(rates or {})
    return out


def cost_for_row(row, details=True, enabled=None):
    """A usage row -> {"cny", "known", "band", "source", "source_at", "backfilled"}
    外加悬停要用的价格明细（rates / unit / currency / usd_cny / or_id / via /
    inherited_from / override_from / band_note / via_derived）。

    The row's own policy reference wins; a row written before references
    existed falls back to the timeline, and a model with no policy at all is
    priced from the factory snapshot. This is the single place that decides
    which price a request is measured against, so the per-row view and every
    summary agree by construction.

    明细只解释这一行用的是哪份价，未定价时整组 None（不编 0）。

    总开关关闭时整块功能停摆：不查策略、不查快照、不折算，直接按「未定价」
    返回并打上 disabled 标记，面板据此显示「—」；与真正没有价的模型走同一条
    路径，但汇总侧能区分「没价」和「功能关着」，不会误报未定价清单。

    `details=False` 是聚合扫描（/usage 快照、指标页整表）用的：那两处每行
    只读 `known` / `cny`（外加 disabled 标记），悬停明细构造出来就被丢掉，
    而每行都要为此付 policy_entry + _details_for 的钱。逐行展示路径（最近
    请求的悬停气泡）不传这个参数，明细照旧。

    `enabled` 是同一件事对总开关的延伸：聚合扫描在循环外把开关问一次传进来
    （None 表示逐行自己查，逐行路径「每行都查、改设置当场生效」的原语义不
    变）。聚合因此看到的是扫描开始那一刻的开关值：设置改动从下一次扫描起
    生效——整表本来就是一次快照，这与其它字段的口径一致。
    """
    if not row or not (pricing_enabled() if enabled is None else enabled):
        cost = {"cny": 0.0, "known": False, "band": None, "source": "builtin",
                "source_at": None, "backfilled": False}
        if row:
            cost["disabled"] = True
        if details:
            cost.update(_no_details())
        return cost
    model = row.get("model")
    pid = row.get("cost_policy")
    backfilled = False
    if not pid:
        pid, backfilled = policy_ref_at(row.get("at"), model)
    policy = load_policies().get(pid) if pid else None
    if policy:
        cost = compute_row(row, pricing=_doc_for(policy, model))
        cost["source"] = pid
        cost["source_at"] = _as_float(policy.get("first_seen"))
        cost["backfilled"] = backfilled
        if details:
            cost.update(_details_for(cost, policy_entry(policy), policy, model))
        return cost
    doc = load_pricing()
    entry = (doc.get("models") or {}).get(model)
    cost = compute_row(row, pricing=doc)
    cost["source"] = "builtin"
    cost["source_at"] = None
    cost["backfilled"] = False
    if details:
        cost.update(_details_for(cost, entry, doc.get("meta"), model))
    return cost


def policy_label(policy):
    """A policy's wall-clock label (when its price was first seen)."""
    stamp = _as_float((policy or {}).get("first_seen"))
    return time.strftime("%Y-%m-%d %H:%M", time.localtime(stamp)) if stamp else None


# ---- background refresh ------------------------------------------------------
# The gateway refreshes the price history on its own schedule; the interval is
# a panel setting in minutes (0 turns it off). A failed fetch changes nothing,
# so the last good version keeps pricing requests. Prices only move a policy
# when they actually change, so a short interval costs one HTTP GET per cycle
# and nothing else.

DEFAULT_REFRESH_MINUTES = 5


class PriceRefresher(threading.Thread):
    """Periodically append a fresh OpenRouter version to the history."""

    def __init__(self, interval_minutes=DEFAULT_REFRESH_MINUTES):
        super().__init__(daemon=True, name="price-refresher")
        self.interval_minutes = max(0.0, _as_float(interval_minutes))
        self.last_run = None
        self.last_error = None
        self.last_models = 0
        self.last_extra = 0
        self._extra_ids = []
        self.last_unpriced = []
        self.next_run = None
        self.logs = []
        self._stop_event = threading.Event()
        self._wake = threading.Event()
        self._run_lock = threading.Lock()
        self._gap_lock = threading.Lock()
        self._gap_cache = None

    def log(self, msg):
        stamp = time.strftime("%Y-%m-%d %H:%M:%S")
        self.logs.append("[%s] %s" % (stamp, msg))
        if len(self.logs) > 40:
            self.logs = self.logs[-40:]
        try:
            gateway_module().add_log_entry("[定价] %s" % msg, tag="pricing")
        except Exception:
            pass

    def interval_seconds(self):
        """The current interval in seconds - the one place the unit is applied."""
        return max(0.0, _as_float(self.interval_minutes)) * 60.0

    def set_interval(self, minutes):
        """Apply a new interval; a running wait picks it up immediately."""
        self.interval_minutes = max(0.0, _as_float(minutes))
        self._wake.set()

    def wake(self):
        """Nudge a parked refresh loop - used when the master switch flips."""
        self._wake.set()

    def stop(self):
        self._stop_event.set()
        self._wake.set()

    def live_ids(self):
        """The gateway's live catalogue ids, filtered the way /v1/models is.

        These are the models the picker can offer but the bundled snapshot has
        never heard of - exactly the ones this change exists for. Read through
        the running gateway module so both sides apply one filter (is_chat_model
        plus the variant/free-sibling rules in curate_remote_catalog), never a
        second copy of the rules and never a second copy of the module: that
        twin would have no account pool, and the live half would read empty.
        Both realms are asked: the remote catalogue is fetched per realm
        (fetch_remote_product_config only knows intl/cn), and a model the
        picker shows on either tab belongs in the price input. Any failure
        falls back to an empty list: the static catalogue must still be priced,
        so live trouble can only ever leave a gap, never shrink the coverage.
        """
        try:
            gateway = gateway_module()
            known = set(hub_model_ids())
            out, seen = [], set()
            for realm in LIVE_CATALOG_REALMS:
                try:
                    entries, _extras = gateway.curated_live_sources(realm)
                except Exception as exc:
                    self.log("live 目录取不到（%s），该区域本轮只按内置目录：%s"
                             % (realm, exc))
                    continue
                for mid, _meta in entries or []:
                    mid = str(mid or "").strip()
                    if mid and mid not in known and mid not in seen:
                        seen.add(mid)
                        out.append(mid)
            return out
        except Exception as exc:
            self.log("live 目录取不到，本轮只覆盖内置目录：%s" % exc)
            return []

    def run_once(self):
        """抓一次并入账。返回 (ok, message)。"""
        with self._run_lock:
            # Re-read the master switch inside the lock: a cycle started just
            # before the panel turned pricing off must not write a fresh
            # policy table on its way out.
            if not pricing_enabled():
                return False, "价估算已关闭"
            try:
                or_models = fetch_openrouter()
            except Exception as exc:
                self.last_error = str(exc)
                self.log("抓取失败，继续用上一版价格：%s" % exc)
                return False, str(exc)
            extra_ids = self.live_ids()
            previous = (load_pricing().get("models") or {})
            doc, unpriced, overridden = build_snapshot(or_models, previous, extra_ids)
            if not doc["models"]:
                self.last_error = "抓到了模型列表，但一个都没匹配上"
                self.log(self.last_error)
                return False, self.last_error
            stamp = time.time()
            added, _changed, assignment = record_policies(doc, at=stamp)
            # The on-demand path reads this index; published only after the
            # fetch really succeeded, so a failed cycle keeps the last good one.
            remember_live_index(or_models)
            self.last_run = stamp
            self.last_error = None
            self.last_models = len(doc["models"])
            self.last_extra = len(extra_ids)
            # Kept for the panel's gap report, which must show a live-only name
            # that could not be priced too - that is the case the whole
            # unpriced view exists for. Memory only, no network on that path.
            self._extra_ids = list(extra_ids)
            self.last_unpriced = list(unpriced)
            self.invalidate_gaps()
            removed = []
            if added:
                # Only a price never seen before can orphan an older one, so
                # the sweep runs when there is something new - not every cycle.
                removed = prune_policies(protect=set(assignment.values()))
            self.log("已取价：%d 个模型（新增策略 %d，人工覆盖 %d，未定价 %d%s%s）"
                     % (self.last_models, added, len(overridden), len(unpriced),
                        "，live 新增 %d" % self.last_extra if self.last_extra else "",
                        "，清理无用策略 %d" % len(removed) if removed else ""))
            return True, ""

    # ---- unpriced visibility (panel) ----------------------------------------
    def invalidate_gaps(self):
        with self._gap_lock:
            self._gap_cache = None

    def gap_report(self, max_items=200, ttl=30.0):
        """(items, summary) - which models show a dash, and why. Panel view.

        Computed from the in-memory index and the stored policy table, plus the
        live ids of the last good cycle - a model the upstream just added and
        OpenRouter does not carry has to be visible here, that is the gap an
        operator can close by hand. Cached for a moment because the settings
        page polls it.
        """
        with self._gap_lock:
            cached = self._gap_cache
            if cached and time.time() - cached["at"] < ttl:
                return cached["items"], cached["summary"]
        or_models, by_norm = live_index()
        _at, assignment = current_assignment()
        items, summary = gap_items(or_models, by_norm, extra_ids=self._extra_ids,
                                   variants=variant_inherit_enabled(),
                                   priced=set(assignment))
        if max_items and len(items) > max_items:
            items = items[:max_items]
        with self._gap_lock:
            self._gap_cache = {"at": time.time(), "items": items, "summary": summary}
        return items, summary

    def run(self):
        # 两种情况要立刻抓一次价：首次启动还没有任何价格历史（面板才立刻有
        # 东西可看），以及总开关刚从关闭切回打开。后者是补算的关键——关闭
        # 期间没有取价，打开后这一份会落到关闭期间那些请求上：先有价、后被
        # 调用过的模型按 policy_ref_at 的补算分支取到它（面板标 `*`），关闭
        # 期间才第一次出现的模型则靠这次取价进入策略表。已经取过价的正常
        # 重启不重复抓。
        first = True
        came_from_off = False
        while not self._stop_event.is_set():
            if not pricing_enabled():
                # 总开关关着：不取价也不计时。面板拨回打开时会唤醒本线程，
                # 循环每轮都重读开关，所以打开后立刻恢复。
                self.next_run = None
                self._wake.wait()
                self._wake.clear()
                came_from_off = True
                continue
            seconds = self.interval_seconds()
            if seconds <= 0:
                self.next_run = None
                self._wake.wait()
                self._wake.clear()
                came_from_off = True
                continue
            if first or came_from_off:
                should_fetch = came_from_off or not load_timeline()
                first = False
                came_from_off = False
                if should_fetch:
                    try:
                        self.run_once()
                    except Exception as exc:
                        self.log("首次抓取异常：%s" % exc)
            self.next_run = time.time() + seconds
            if self._wake.wait(seconds):
                self._wake.clear()
                continue
            if self._stop_event.is_set():
                break
            try:
                self.run_once()
            except Exception as exc:
                self.last_error = str(exc)
                self.log("刷新异常：%s" % exc)

    def status(self):
        policies = load_policies()
        at, assignment = current_assignment()
        gaps, gap_summary = self.gap_report()
        master = pricing_enabled()
        return {
            "interval_minutes": self.interval_minutes,
            # 总开关关着时，无论间隔填多少都不取价，所以 enabled 是两者相与；
            # master_enabled 单独回报开关本身，面板据此渲染设置页。
            "enabled": master and self.interval_minutes > 0,
            "master_enabled": master,
            "running": self.is_alive(),
            "last_run": self.last_run,
            "last_run_label": (time.strftime("%Y-%m-%d %H:%M",
                                             time.localtime(self.last_run))
                               if self.last_run else None),
            "next_run": self.next_run,
            "next_run_label": (time.strftime("%Y-%m-%d %H:%M",
                                             time.localtime(self.next_run))
                               if self.next_run else None),
            "last_error": self.last_error,
            "last_models": self.last_models,
            "last_extra": self.last_extra,
            "policies": len(policies),
            "models": len(assignment),
            "current_at": at,
            "current_at_label": (time.strftime("%Y-%m-%d %H:%M",
                                               time.localtime(at)) if at else None),
            # What is in force right now, model by model: the declaration the
            # panel shows, and the answer to "which policy is live". A variant
            # says so, with the model it inherited its price from.
            "current": {m: {"id": pid,
                            "label": policy_label(policies.get(pid) or {}),
                            "via": (policies.get(pid) or {}).get("via") or "direct",
                            "inherited_from": (policies.get(pid) or {}).get("inherited_from")}
                        for m, pid in sorted(assignment.items())},
            "gaps": gaps,
            "gap_summary": gap_summary,
            "variant_inherit": variant_inherit_enabled(),
            "overrides_file": overrides_path(),
            "policies_file": policies_path(),
            "timeline": timeline_path(),
            "logs": list(self.logs),
        }
